### YamlMime:ManagedReference
items:
- uid: Mcma.Api.Routes
  commentId: N:Mcma.Api.Routes
  id: Mcma.Api.Routes
  children:
  - Mcma.Api.Routes.DelegateMcmaApiRoute
  - Mcma.Api.Routes.IMcmaApiRoute
  - Mcma.Api.Routes.IMcmaApiRouteCollection
  - Mcma.Api.Routes.McmaApiRoute
  - Mcma.Api.Routes.McmaApiRouteCollection
  langs:
  - csharp
  - vb
  name: Mcma.Api.Routes
  nameWithType: Mcma.Api.Routes
  fullName: Mcma.Api.Routes
  type: Namespace
  assemblies:
  - Mcma.Api
references:
- uid: Mcma.Api.Routes.DelegateMcmaApiRoute
  commentId: T:Mcma.Api.Routes.DelegateMcmaApiRoute
  name: DelegateMcmaApiRoute
  nameWithType: DelegateMcmaApiRoute
  fullName: Mcma.Api.Routes.DelegateMcmaApiRoute
- uid: Mcma.Api.Routes.IMcmaApiRoute
  commentId: T:Mcma.Api.Routes.IMcmaApiRoute
  parent: Mcma.Api.Routes
  name: IMcmaApiRoute
  nameWithType: IMcmaApiRoute
  fullName: Mcma.Api.Routes.IMcmaApiRoute
- uid: Mcma.Api.Routes.IMcmaApiRouteCollection
  commentId: T:Mcma.Api.Routes.IMcmaApiRouteCollection
  parent: Mcma.Api.Routes
  name: IMcmaApiRouteCollection
  nameWithType: IMcmaApiRouteCollection
  fullName: Mcma.Api.Routes.IMcmaApiRouteCollection
- uid: Mcma.Api.Routes.McmaApiRoute
  commentId: T:Mcma.Api.Routes.McmaApiRoute
  parent: Mcma.Api.Routes
  name: McmaApiRoute
  nameWithType: McmaApiRoute
  fullName: Mcma.Api.Routes.McmaApiRoute
- uid: Mcma.Api.Routes.McmaApiRouteCollection
  commentId: T:Mcma.Api.Routes.McmaApiRouteCollection
  parent: Mcma.Api.Routes
  name: McmaApiRouteCollection
  nameWithType: McmaApiRouteCollection
  fullName: Mcma.Api.Routes.McmaApiRouteCollection
- uid: Mcma.Api.Routes
  commentId: N:Mcma.Api.Routes
  name: Mcma.Api.Routes
  nameWithType: Mcma.Api.Routes
  fullName: Mcma.Api.Routes
