### YamlMime:UniversalReference
items:
  - uid: azure-client.ConfigurationWithTenant
    name: ConfigurationWithTenant
    fullName: ConfigurationWithTenant
    children: []
    langs:
      - typeScript
    type: type alias
    summary: ''
    syntax:
      content: 'type ConfigurationWithTenant = Configuration & { tenant: string }'
    package: azure-client
