### YamlMime:UniversalReference
items:
  - uid: client.getResourceManagerConfig
    name: getResourceManagerConfig(ConfigVariables)
    children: []
    type: function
    langs:
      - typeScript
    summary: ''
    syntax:
      content: 'function getResourceManagerConfig(configVariables: ConfigVariables)'
      parameters:
        - id: configVariables
          type:
            - ConfigVariables
          description: ''
      return:
        type:
          - client.ResourceManagerConfig
        description: ''
    package: client
references:
  - uid: client.ResourceManagerConfig
    name: ResourceManagerConfig
    spec.typeScript:
      - name: ResourceManagerConfig
        fullName: ResourceManagerConfig
        uid: client.ResourceManagerConfig
